# Gradle Versions Plugin 설정 되어있지 않으면 check_dependency_updates 커맨드에서 에러가 발생할 것 같습니다.
version: 2.1
orbs:
  android: circleci/android@2.2.0 # https://circleci.com/developer/orbs/orb/circleci/android
  slack: circleci/slack@4.12.1 # https://circleci.com/developer/orbs/orb/circleci/slack
commands:
  chmod_permission:
    description: if permission for Gradlew Dependencies fail, use this.
    steps:
      - run:
          name: Chmod permissions # if permission for Gradlew Dependencies fail, use this.
          command: sudo chmod +x ./gradlew
  install_android_gradle_dependencies:
    steps:
      - android/restore-gradle-cache
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - android/save-gradle-cache
  check_dependency_updates:
    description: 업데이트 가능한 라이브러리 확인 (https://github.com/ben-manes/gradle-versions-plugin)
    parameters:
      revision:
        default: release
        type: string
      output:
        default: plain
        type: string
    steps:
      - run:
          name: Check Dependency Updates
          command: ./gradlew dependencyUpdates -Drevision=<<parameters.revision>> -DoutputFormatter=<<parameters.output>>
  set_build_properties:
    parameters:
      build-number:
        default: $CIRCLE_BUILD_NUM
        type: string
      build-version:
        default: 1.0.0
        type: string
    steps:
      - run:
          name: Set Build Properties
          command: sudo chmod +x ./setBuildProperties; ./setBuildProperties <<parameters.build-number>> "<<parameters.build-version>>"
  build_and_archive: # TODO : 여기는 좀 더 개선이 필요할듯
    parameters:
      command:
        default: assembleRelease
        type: string
      path:
        default: app/build/outputs/apk/release
        type: string
      source:
        default: app-release.apk
        type: string
      target:
        type: string
      destination:
        default: apk
        type: string
    steps:
      - run:
          name: Check Java Version
          command: java --version
      - run:
          name: Build Binaries
          command: ./gradlew <<parameters.command>>
      - run:
          name: Change File Name
          command: mv <<parameters.path>>/<<parameters.source>> <<parameters.path>>/<<parameters.target>>
      - store_artifacts:
          path: <<parameters.path>>
          destination: <<parameters.destination>>
  slack_notify:
    steps:
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: basic_success_1
jobs:
  build:
    executor:
      name: android/android-docker
      tag: 2023.04.1 # https://circleci.com/developer/images/image/cimg/android#image-tags
    steps:
      - checkout
      - android/change-java-version:
          java-version: 17
      - chmod_permission
      - android/decode-keystore:
          keystore-location: ./keystore # create-keystore-properties 기본값
      - android/create-keystore-properties
      - install_android_gradle_dependencies
      - check_dependency_updates
      - set_build_properties
      - build_and_archive:
          target: CSTemplate-v${CIRCLE_BUILD_NUM}.apk
      - slack_notify
workflows:
  build:
    jobs:
      - build