version: 2.1
orbs:
  android: circleci/android@2.2.0 # https://circleci.com/developer/orbs/orb/circleci/android for latest version
  slack: circleci/slack@4.10.1
commands:
  install_android_gradle_dependencies:
    steps:
      - android/restore-gradle-cache
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - android/save-gradle-cache
jobs:
  build:
    executor:
      name: android/android-docker
      tag: 2023.04.1
    steps:
      - checkout
      - android/change-java-version:
          java-version: 17
      - run:
          name: Chmod permissions # if permission for Gradlew Dependencies fail, use this.
          command: sudo chmod +x ./gradlew
      - android/create-keystore-properties:
          release-keystore: keystore
      - install_android_gradle_dependencies
      - run:
          name: Check Dependency Updates
          command: ./gradlew dependencyUpdates -Drevision=release -DoutputFormatter=plain
      - run:
          name: Set Build Properties
          command: sudo chmod +x ./setBuildProperties; ./setBuildProperties $CIRCLE_BUILD_NUM "1.0.0"
      - run:
          name: Build Binaries
          command: ./gradlew assembleRelease;mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/CSTemplateM3-release-${CIRCLE_BUILD_NUM}.apk
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: basic_success_1
      - store_artifacts:
          path: app/build/outputs/apk/release
          destination: apk
workflows:
  build:
    jobs:
      - build