name: "Chmod Permission"
description: "Chmod Permission"
inputs:
  revision:
    description: "revision"
    required: false
    default: "release"
  format:
    description: "format"
    required: false
    default: "plain"
runs:
  using: "composite"
  steps:
    - run: ./gradlew dependencyUpdates -Drevision=${{ inputs.revision }} -DoutputFormatter=${{ inputs.format }}
      shell: bash